# Generated by Django 3.2.4 on 2025-09-21 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('autobiography', models.TextField(blank=True, verbose_name='Автобиография')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2025, 'Год издания не может быть больше текущего.')], verbose_name='Год издания')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('preface', models.TextField(blank=True, verbose_name='Предисловие')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author', verbose_name='Автор книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'default_related_name': 'books',
            },
        ),
    ]
